export { default as Home } from './Home'
export { default as Services } from './Services'
export { default as Portfolio } from './Portfolio'
export { default as Clocks } from './Clocks'
export { default as Contact } from './Contact'